"""Voxel structure schema and deterministic checks.

This module is the compiler side of the pipeline: it decides whether a proposed
structure is acceptable under stated assumptions. It never calls an LLM, and it
establishes validity only against the rules implemented here. It does not
establish real friction, calibration accuracy, magnetic behavior, dynamic
stability, or reliable execution.
"""
from dataclasses import dataclass, field
from pathlib import Path
import json
import sys

SIM = Path(__file__).resolve().parent.parent/'sim'
if str(SIM) not in sys.path:
    sys.path.insert(0, str(SIM))
from cube_colors import COLORS  # noqa: E402  single source of truth for colors

SCHEMA_VERSION = 1
# Nominal cube size confirmed by the user. Measured stack pitch is a separate
# calibration quantity and is deliberately not represented here.
NOMINAL_CUBE_SIZE_M = .0254
# Provisional limits. Real inventory, reachable footprint, and a validated layer
# count are not confirmed; override them explicitly per build.
DEFAULT_LIMITS = {'max_cubes': 64, 'max_layers': 4, 'max_footprint': 12}


@dataclass(frozen=True)
class Voxel:
    """One cube at integer grid coordinates. z=0 rests on the build surface."""
    x: int
    y: int
    z: int
    color: str

    @property
    def cell(self):
        return self.x, self.y, self.z


@dataclass
class Structure:
    structure_id: str
    name: str
    voxels: list
    cube_size_m: float = NOMINAL_CUBE_SIZE_M
    # Where the model came from: a model id, or 'offline_library'. Never claim a
    # hand-authored structure was generated by a model.
    source: str = 'unspecified'
    prompt: str = ''
    schema_version: int = SCHEMA_VERSION

    def to_dict(self):
        return {'schema_version': self.schema_version, 'structure_id': self.structure_id,
                'name': self.name, 'cube_size_m': self.cube_size_m, 'source': self.source,
                'prompt': self.prompt,
                'voxels': [{'x': v.x, 'y': v.y, 'z': v.z, 'color': v.color} for v in self.voxels]}

    @classmethod
    def from_dict(cls, d):
        if not isinstance(d, dict):
            raise TypeError('structure must be a JSON object')
        voxels = d.get('voxels')
        if not isinstance(voxels, list):
            raise TypeError('voxels must be a list')
        parsed = []
        for i, v in enumerate(voxels):
            if not isinstance(v, dict):
                raise TypeError(f'voxel {i} must be an object')
            missing = {'x', 'y', 'z', 'color'} - set(v)
            if missing:
                raise TypeError(f'voxel {i} is missing {sorted(missing)}')
            parsed.append(Voxel(v['x'], v['y'], v['z'], v['color']))
        return cls(structure_id=d.get('structure_id', ''), name=d.get('name', ''),
                   voxels=parsed, cube_size_m=d.get('cube_size_m', NOMINAL_CUBE_SIZE_M),
                   source=d.get('source', 'unspecified'), prompt=d.get('prompt', ''),
                   schema_version=d.get('schema_version', SCHEMA_VERSION))


@dataclass
class Problem:
    code: str
    message: str
    cell: tuple = None

    def __str__(self):
        where = f' at {self.cell}' if self.cell else ''
        return f'[{self.code}]{where} {self.message}'


@dataclass
class Report:
    problems: list = field(default_factory=list)
    counts: dict = field(default_factory=dict)

    @property
    def ok(self):
        return not self.problems

    def codes(self):
        return sorted({p.code for p in self.problems})


def _is_int(value):
    # bool is an int subclass; a True coordinate is a schema error, not a 1.
    return isinstance(value, int) and not isinstance(value, bool)


def validate(structure, limits=None, inventory=None):
    """Check a structure against schema, budget, support, and connectivity rules.

    Returns a Report. An empty problem list means the structure satisfies these
    rules, not that the robot can physically build it.
    """
    limits = {**DEFAULT_LIMITS, **(limits or {})}
    problems = []
    add = lambda code, message, cell=None: problems.append(Problem(code, message, cell))

    if not isinstance(structure.structure_id, str) or not structure.structure_id.strip():
        add('missing_id', 'structure_id must be a non-empty string')
    if structure.schema_version != SCHEMA_VERSION:
        add('schema_version', f'expected schema version {SCHEMA_VERSION}, '
                              f'got {structure.schema_version!r}')
    size = structure.cube_size_m
    if not isinstance(size, (int, float)) or isinstance(size, bool) or not size > 0:
        add('cube_size', 'cube_size_m must be a positive number')
    elif abs(size - NOMINAL_CUBE_SIZE_M) > 1e-9:
        add('cube_size', f'cube_size_m {size} does not match the confirmed '
                         f'{NOMINAL_CUBE_SIZE_M} m cube')

    if not structure.voxels:
        add('empty', 'a structure needs at least one voxel')
        return Report(problems, {'cubes': 0})

    occupied = {}
    for v in structure.voxels:
        if not all(_is_int(getattr(v, axis)) for axis in 'xyz'):
            add('non_integer', 'voxel coordinates must be integers', (v.x, v.y, v.z))
            continue
        if v.z < 0:
            add('negative_layer', 'layers below the build surface do not exist', v.cell)
            continue
        if v.color not in COLORS:
            add('unknown_color', f'unsupported color {v.color!r}; '
                                 f'choose from {sorted(COLORS)}', v.cell)
        if v.cell in occupied:
            add('duplicate', 'two cubes cannot occupy one cell', v.cell)
            continue
        occupied[v.cell] = v.color

    if not occupied:
        return Report(problems, {'cubes': 0})

    xs = [c[0] for c in occupied]
    ys = [c[1] for c in occupied]
    layers = max(c[2] for c in occupied) + 1
    footprint = (max(xs)-min(xs)+1, max(ys)-min(ys)+1)
    counts = {'cubes': len(occupied), 'layers': layers, 'footprint': footprint,
              'colors': {c: sum(1 for v in occupied.values() if v == c)
                         for c in sorted(set(occupied.values()))}}

    if len(occupied) > limits['max_cubes']:
        add('cube_budget', f'{len(occupied)} cubes exceeds the {limits["max_cubes"]} budget')
    if layers > limits['max_layers']:
        add('layer_budget', f'{layers} layers exceeds the {limits["max_layers"]} limit')
    if max(footprint) > limits['max_footprint']:
        add('footprint', f'footprint {footprint} exceeds {limits["max_footprint"]} cells')
    for color, needed in counts['colors'].items():
        available = (inventory or {}).get(color)
        if available is not None and needed > available:
            add('inventory', f'needs {needed} {color} cubes, {available} available')

    # Direct support only. This deliberately excludes overhangs: a cube whose
    # neighbours are occupied but whose own cell below is empty is rejected.
    for cell in sorted(occupied):
        x, y, z = cell
        if z and (x, y, z-1) not in occupied:
            add('unsupported', 'no cube directly below; overhangs are not supported', cell)

    # Single 6-connected component, so the build is one object.
    start = min(occupied)
    seen, stack = {start}, [start]
    while stack:
        x, y, z = stack.pop()
        for step in [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]:
            cell = (x+step[0], y+step[1], z+step[2])
            if cell in occupied and cell not in seen:
                seen.add(cell)
                stack.append(cell)
    if len(seen) != len(occupied):
        stranded = len(occupied)-len(seen)
        add('disconnected', f'{stranded} cube{"s" if stranded > 1 else ""} '
                            f'{"are" if stranded > 1 else "is"} not connected to the main body')
    return Report(problems, counts)


def build_order(structure):
    """Deterministic bottom-up placement order.

    This is an ordering only. It does not produce tool poses, check finger
    clearance, or verify that the arm can reach any cell; that is the executor's
    job and is not implemented yet.
    """
    return sorted(structure.voxels, key=lambda v: (v.z, v.y, v.x))


def load(path):
    return Structure.from_dict(json.loads(Path(path).read_text()))


def save(structure, path):
    Path(path).write_text(json.dumps(structure.to_dict(), indent=2)+'\n')
    return path
